app = "staypilot"
primary_region = "cdg"

[build]

[env]
PORT = "8080"
NODE_ENV = "production"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1

[mounts]
source = "staypilot_data"
destination = "/data"
